owner: kuzzleio
repo: status-page
user-agent: kuzzleio
skipDescriptionUpdate: true
skipTopicsUpdate: true
skipHomepageUpdate: true

sites:
  - name: Kuzzle Website
    url: https://kuzzle.io
  - name: Kuzzle Blog
    url: https://blog.kuzzle.io
  - name: Kuzzle Docs
    url: https://docs.kuzzle.io
  - name: PaaS Packages
    url: $SITE_URL_PAAS_PACKAGES

status-website:
  cname: status.kuzzle.io
  logoUrl: https://status.kuzzle.io/kuzzle.svg
  favicon: https://status.kuzzle.io/favicon.png
  themeUrl: https://status.kuzzle.io/kuzzle.css
  name: Kuzzle Status
  navbar:
    - title: Status
      href: /
    - title: Kuzzle
      href: https://kuzzle.io
    - title: GitHub
      href: https://github.com/$OWNER

commitMessages:
  readmeContent: "docs(readme): update summary [skip ci] [upptime]"
  summaryJson: "chore: update status summary [skip ci] [upptime]"
  graphsUpdate: "chore: update graphs [skip ci] [upptime]"
