owner: kuzzleio
repo: status-page
user-agent: kuzzleio
skipDescriptionUpdate: true
skipTopicsUpdate: true
skipHomepageUpdate: true

sites:
  - name: Kuzzle Website
    url: https://kuzzle.io
  - name: Kuzzle Blog
    url: https://blog.kuzzle.io
  - name: Kuzzle Docs
    url: https://docs.kuzzle.io
  - name: "Discord #1"
    url: https://discord-redirect.app.kuzzle.io
    expectedStatusCodes:
      - 302
  - name: "Discord #2"
    url: https://join.discord.kuzzle.io
    expectedStatusCodes:
      - 302
  - name: PaaS Console (API)
    url: $SITE_URL_PAAS_CONSOLE_API
  - name: PaaS Console (Web)
    url: $SITE_URL_PAAS_CONSOLE_WEB
  - name: PaaS Packages
    url: $SITE_URL_PAAS_PACKAGES
  - name: PaaS Container registry
    url: $SITE_URL_PAAS_CONTAINER_REGISTRY
  - name: PaaS CD
    url: $SITE_URL_PAAS_CD
  - name: PaaS SSO
    url: $SITE_URL_PAAS_SSO
  - name: PaaS LNS (Web)
    url: $SITE_URL_PAAS_LNS_WEB
  - name: PaaS LNS (MQTT)
    check: "tcp-ping"
    url: $SITE_URL_PAAS_LNS_MQTT
    port: $SITE_PORT_PAAS_LNS_MQTT

status-website:
  cname: status.kuzzle.io
  logoUrl: https://status.kuzzle.io/kuzzle.svg
  favicon: https://status.kuzzle.io/favicon.png
  themeUrl: https://status.kuzzle.io/kuzzle.css
  name: Kuzzle Status
  navbar:
    - title: Status
      href: /
    - title: Kuzzle
      href: https://kuzzle.io
    - title: GitHub
      href: https://github.com/$OWNER

commitMessages:
  readmeContent: "docs(readme): update summary [skip ci] [upptime]"
  summaryJson: "chore: update status summary [skip ci] [upptime]"
  graphsUpdate: "chore: update graphs [skip ci] [upptime]"
