# Export the secret from the Scaleway CLI for the S3 backend
export AWS_ACCESS_KEY_ID := `scw config get access-key`
export AWS_SECRET_ACCESS_KEY := `scw config get secret-key`

init:
    terraform init

preview:
    terraform plan

apply:
    terraform apply

export-keys:
    echo "export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID"
    echo "export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY"
